store/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:object_id>/', views.AddCart, name='cart_add'),
    #path('remove/', views.RemovefromCart, name='cart_remove'),
    #path('clear/', views.ClearCart, name='cart_clear'),
    #path('delete/', views.DeleteCart, name='cart_delete'),
]

store/catalog/urls.py
from django.urls import path
from . import views

app_name = 'Catalog'

urlpatterns = [
    path('view/<str:typeslug>/<str:slug>/', views.ViewCatalog, name = 'catalog'),

    path('filter/', views.FilterCatalog, name = 'filter')
]

store/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name = 'home')
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/user/urls.py
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('login/', views.UserLogin, name = 'login'),
    path('login/auth/', views.UserLoginAuth, name = 'LoginAuth'),
    path('logout/', views.UserLogout, name = 'logout'),

    path('register/', views.UserRegister, name = 'register'),
    path('register/auth/', views.UserRegisterAuth, name = 'RegisterAuth'),
    path('register/<str:token>/activate/', views.UserRegisterActivate, name = 'RegisterActivate'),
    path('register/<str:link>/sender/', views.UserRegisterSend, name = 'RegisterSend'),

    path('register/validator/', views.UserRegisterValidator, name = 'RegisterValidator'),
]

store/catalog/models.py
from django.db import models
import datetime


#-------Categories----------------
class Country(models.Model):
    country = models.CharField(max_length = 300, verbose_name = 'страна производитель', unique = True)
    slug = models.CharField(max_length = 400 , verbose_name = 'url')

    class Meta:
        verbose_name = 'категория (Страна)'
        verbose_name_plural = 'Категории (Страна)'

    def __str__(self):
        return self.country

    def get_short_name(self):
        return self.country

    def save(self, *args, **kwargs):
        self.country = self.country.lower()
        return super(Country, self).save(*args, **kwargs)


class Manufacturer(models.Model):
    manufacturer = models.CharField(max_length= 400, verbose_name = 'произовдитель', unique = True)
    
    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.manufacturer
    
    def get_short_name(self):
        return self.manufacturer

    def save(self, *args, **kwargs):
        self.manufacturer= self.manufacturer.lower()
        return super(Manufacturer, self).save(*args, **kwargs)




class MainType(models.Model):
    Type = models.CharField(max_length = 200, unique = True)
    typeslug = models.CharField(max_length = 200, verbose_name = 'url', null=True)

    class Meta:
        verbose_name = 'Главный вид'
        verbose_name_plural = 'Главный вид'

    def __str__(self):
        return self.Type

    def get_short_name(self):
        return self.Type

    def save(self, *args, **kwargs):
        self.Type = self.Type.lower()
        return super(MainType, self).save(*args, **kwargs)






class TeaType(models.Model):
    Type = models.CharField(max_length = 200, verbose_name = 'тип/вид чая', unique = True)
    slug = models.CharField(max_length = 400 , verbose_name = 'url')
    image = models.ImageField(upload_to = 'media/TeaType', default = 'media/NoImageAvailable.png', null = True)
    maintype = models.ForeignKey(MainType, blank = True, on_delete = models.CASCADE, null = True)

    class Meta:
        verbose_name = 'категория (Тип чая)'
        verbose_name_plural = 'Категории (Тип чая)'

    def __str__(self):
        return self.Type

    def get_short_name(self):
        return self.Type

    def save(self, *args, **kwargs):
        self.Type = self.Type.lower()
        return super(TeaType, self).save(*args, **kwargs)



class TeaTypeFavor(models.Model):
    Type = models.CharField(max_length = 200, verbose_name = 'аромат чая', unique = True)
    slug = models.CharField(max_length = 400 , verbose_name = 'url')

    class Meta:
        verbose_name = 'категория (аромат чая)'
        verbose_name_plural = 'Категории (аромат чая)'

    def __str__(self):
        return self.Type

    def get_short_name(self):
        return self.Type

    def save(self, *args, **kwargs):
        self.Type = self.Type.lower()
        return super(TeaTypeFavor, self).save(*args, **kwargs)



#------PRODUCT---------------
class product(models.Model):
    name = models.CharField(max_length=200, verbose_name='название', unique=True)
    slug = models.SlugField(max_length=200, verbose_name='url', unique=True)
    ProductAvt = models.ImageField(upload_to = 'media/productsAvt/', default = 'media/NoImageAvailable.png', blank=True)
    ProductMain = models.ImageField(upload_to = 'media/products/', default = 'media/NoImageAvailable.png', blank=True)
    price = models.IntegerField(verbose_name='цена')
    added = models.DateTimeField(default = datetime.datetime.now)
    available = models.BooleanField(default = True)

    country = models.ForeignKey(Country, verbose_name='страна производитель', on_delete = models.CASCADE, related_name = 'city')
    TeaType = models.ForeignKey(TeaType, verbose_name='тип/вид чая', on_delete=models.CASCADE, null = True, related_name = 'tea_type')
    TeaTypeFavor = models.ForeignKey(TeaTypeFavor, verbose_name='аромат чая', on_delete = models.CASCADE, null = True, related_name = 'type_favor')
    manufacturer = models.ForeignKey(Manufacturer, verbose_name='производитель', on_delete = models.CASCADE, null = True, default = 'собственное')

    class Meta:
        ordering = ['-added',]
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'


    def __str__(self):
        return self.name

    def get_short_name(self):
        return self.name





#------PRODUCT DESCRIPTION------
class description(models.Model):
    product = models.ForeignKey(product, related_name = 'item', on_delete=models.CASCADE)
    descriptionKey = models.CharField(max_length = 100, verbose_name = 'характеристика')
    descriptionValue = models.TextField(max_length = 400, verbose_name = 'описание')
    image = models.ImageField(upload_to = 'media/productDescription/', blank = True)
    is_big = models.BooleanField(default = False, verbose_name = 'описание?')

    def __str__(self):
        return self.product.name

    def get_short_name(self):
        return self.product.name

store/catalog/forms.py
from django import forms

class PriceForm(forms.Form):
    price_from = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-price_from form-price', 'id': 'form-price_from', 'value': 'form-price-from'}))
    price_to = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-price_to form-price', 'id': 'form-price_to', 'value': 'form-price-to'}))

store/catalog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse

from .models import Manufacturer, TeaType, MainType, product
from django.db.models import Max, Min
from django.db.models import Q

from .forms import PriceForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from django.http import JsonResponse
from django.template.loader import render_to_string



def ViewCatalog(request, typeslug, slug):
    #--------------GETTING PRODUCTS BY URL PARAMETERS------
    maintype = MainType.objects.get(typeslug = typeslug)
    teatype = TeaType.objects.get(slug=slug, maintype = maintype)
    products = product.objects.filter(TeaType=teatype)

    #-------------INIT FORM FOR PRICE FIELDS AND SET INTIAL DATA WITH MAX AND MIN PRICE OF AVAILABLE PRODUCTS------
    initial_data = {
        'price_from': (product.objects.filter(TeaType=teatype).aggregate(Min('price'))['price__min']),
        'price_to': (product.objects.filter(TeaType=teatype).aggregate(Max('price'))['price__max'])
    }

    priceform = PriceForm(request.GET or None, initial = initial_data)


    #-------GET ALL UNIQUE COUNTRY AND FAVORS VALUES USED IN MODEL OBJECTS
    CategoriesFavor = []
    CategoriesCountry = []
    CategoriesManufacturer = []
    for categories in products:

        if str(categories.TeaTypeFavor) in CategoriesFavor and str(categories.TeaTypeFavor) != None:
            pass
        else:
            CategoriesFavor.append(str(categories.TeaTypeFavor))

        if str(categories.country) in CategoriesCountry and str(categories.country) != None: 
            pass
        else:
            CategoriesCountry.append(str(categories.country))

        if str(categories.manufacturer) in CategoriesManufacturer and str(categories.manufacturer) != None:
            pass
        else:
            CategoriesManufacturer.append(str(categories.manufacturer))


    
    #---------PAGINATE PRODUCTS FOR 9 ITEMS PER PAGE-----


    page = request.GET.get('page', 1)
    paginator = Paginator(products, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)



    #----------DATA THAT WILL BE SENDED TO TEMPLATE-------
    data = {
        'URLPARAMATERS' : {'type1': typeslug, 'type2' : slug},
        'products': products,
        'price_form': priceform,
        'CategoriesCountry': CategoriesCountry,
        'CategoriesFavor':  CategoriesFavor,
        'CategoriesMan': CategoriesManufacturer,
    }
    #------RENDER----------
    return render(request, 'main/Catalog.html', data)





#----------AJAX FILTER-------------
def FilterCatalog(request):

    if request.method == 'GET' and request.is_ajax():

        maintype = MainType.objects.get(typeslug = request.GET.get('url-par1'))
        teatype = TeaType.objects.get(slug= request.GET.get('url-par2'), maintype = maintype)
        products = product.objects.filter(TeaType=teatype)

        favors = request.GET.getlist('favor[]')
        countries = request.GET.getlist('country[]')
        manufacturers = request.GET.getlist('manufacturer[]')
        price_from = request.GET.get('form-price_from')
        price_to = request.GET.get('form-price_to')

        if price_from == '' or None:
            price_from = 0
        
        if price_to == '' or None:
            price_to = 0

        products = products.filter(
            Q(price__gte = price_from) &
            Q(price__lte = price_to)
        )

        if len(favors) > 0:
            products = products.filter(TeaTypeFavor__Type__in = favors)
        if len(countries) > 0:
            products = products.filter(country__country__in = countries)
        if len(manufacturers) > 0:
            products = products.filter(manufacturer__manufacturer__in = manufacturers)

        render = render_to_string('renders_for_ajax/Product_AJAX.html', {'products': products})

        return JsonResponse({'render': render})
        
    return HttpResponse('')

store/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'main/home.html')

store/templates/main/Activate.html
{% extends 'main/layout.html' %}
{% load static %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/activate.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class = 'main-container'>
        <img class = 'logo-activate' src = "{% static 'main/images/green-tea-icon.png'%}"></img>
        <p class = 'welcome-header'>Добро пожаловать {{request.user.FirstName}} {{request.user.LastName}}!</p>
        <p class = 'welcome-text'>Ваш аккаунт успешно создан</p>
        <a href="/" class = 'btn btn-success'>На главную</a>
    </div>
    
    
{% endblock %}

store/templates/main/Catalog.html
{% extends 'main/layout.html' %}
{% load static %}


{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/catalog.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class = 'main-container'>


        <div class = 'sticky-block'>
            <div class = 'left-filters'>
                <div class = 'filter-block'>
                    <h2 class = 'filter-header'>Сортировать по</h2>
                <form method = 'GET' id = 'filter-form' data-typeone = '{{ URLPARAMATERS.type1 }}', data-typetwo = '{{ URLPARAMATERS.type2 }}'>

                        <div class = 'favor-category category'>
                            <h4 class = 'category_header'>Тип вкуса</h4>
                            {% for favor in CategoriesFavor %}
                                <div class = 'category-box'>
                                    <input type="checkbox" id ='checkfavor' class = 'check' name = 'favor' value = '{{favor}}'>
                                    <label for = '{{favor}}' class = 'check-label'>{{favor}}</label>
                                </div>
                                <br>
                            {% endfor %}
                        </div>

                        <br>

                        <div class = 'country-category category'>
                            <h4 class = 'category_header'>Выращено в</h4>
                            {% for country in CategoriesCountry %}
                                <div class = 'category-box'>
                                    <input type="checkbox" id ='checkfavor' name = 'country' class = 'check' value = '{{country}}'>
                                    <label for = '{{country}}' class = 'check-label'>{{country}}</label>
                                </div>
                                <br>
                            {% endfor %}
                        </div>

                        <br>

                        <div class = 'manufacturer-category category'>
                            <h4 class = 'category_header'>Производитель</h4>
                            {% for manufacturer in CategoriesMan %}
                                <div class = 'category-box'>
                                    <input type="checkbox" id ='checkfavor' name = 'manufacturer' class = 'check' value = '{{manufacturer}}'>
                                    <label for = '{{manufacturer}}' class = 'check-label'>{{manufacturer}}</label>
                                </div>
                                <br>
                            {% endfor %}
                        </div>

                        <br>

                        <div class = 'price-filter category'>
                            <h4 class = 'category_header'>Цена</h4>
                            {{ price_form.price_from }}
                            <label for ='form-price-to class' class = 'price-label'>-</label>
                            {{ price_form.price_to }}
                        </div>


                    </form>

                </div>
            </div>
        </div>


        <div class  = 'right-catalog'>
            {% for product in products %}
                <a class = 'product-container' href = '#'>
                    <div class = 'product-card'>
                        <br>
                        <img src = '{{product.ProductAvt.url }}' class = 'product-logo'></img>
                        <p class = 'favor text'>{{product.TeaTypeFavor}}</p>
                        <p class = 'name text'>{{product.name}}</p>
                        <p class = 'price-for-100 text'>Цена за 100г: {{product.price}}р</p>
                        <button data-ProductId = '{{product.id}}' data-link = '{% url "cart:cart_add" product.id%}' class = 'add_cart cart' id = 'ajax_cart'  onclick="return false"><i class="fas fa-shopping-bag"></i> В корзину</button>
                    </div>
                </a>
            {% endfor %}

            <br>

            {% if products.has_other_pages %}
                <div class = 'paginator'>

                    <div class = 'paginator-block'>
                        <ul>

                        {% if products.has_previous %}
                            <li class = 'paginator-back paginator-page'><a href="?page={{ products.previous_page_number }}"><</a></li>
                        {% endif %}

                        {% if products.paginator.num_pages > 3%}
                            {% for page in products.paginator.page_range%}
                                {% if products.number == page %}
                                    <li class = 'paginator-page-here paginator-page'><p>{{page}}</p></li>
                                {% elif page >= products.number|add:-1 and page <= products.number|add:1 %}
                                    <li class = 'paginator-pages paginator-page'><a href = "?page={{page}}">{{page}}</a></li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        {% if products.has_next %}
                            <li class = 'paginator-next paginator-page'><a href="?page={{ products.next_page_number }}">></a></li>
                        {% endif %}

                        </ul>
                    </div>
                </div>
            {% endif %}
        </div>

        <script src="{% static 'main/js/CartAjax.js' %}" ></script>
        <script src="{% static 'main/js/FilterAjax.js' %}" ></script>


{% endblock %}

store/templates/main/EmailSended.html
{% extends 'main/layout.html' %}
{% load static %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/EmailSend.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class = 'main-container'>
        <div class = 'email-container'>
            <p class = 'email-sended'>Ссылка на потверждение аккаунта отправлена на вашу почту</p>
            <p class = 'email-not-sended-text'>Не пришла ссылка на активацию?</p>
            <button class = 'btn btn-success btn-email' data-time = {{time}}></button>
            <p class = 'success-text'></p>
        </div>
    </div>
    
    <script src="{% static 'main/js/EmailResender.js' %}"></script>
    
    
{% endblock %}

store/templates/main/home.html
{% extends 'main/layout.html' %}
{% load static %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/home.css' %}">
{% endblock %}

{% block body %}
    <div class = 'main-container'>
        <img class = 'main-image' src = 'https://get.pxhere.com/photo/landscape-field-hill-flower-valley-green-soil-agriculture-highland-terrace-grassland-vegetation-plantation-plateau-india-rural-area-paddy-field-tea-plantation-hill-station-tea-garden-mountainous-landforms-1217816.jpg'>
    </div>
    {{form.email}}
    {{form.password}}
    {{type}}
    HELLO
    
{% endblock %}

store/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href= "{% static 'main/css/layout.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

    {% block settings %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/b269aeb9c3.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class = "navbar-1">
        <div class = "logo-left navbar-block">
            <a class = 'logo-link' href = '/'><img class = 'logo-image' src = "{% static 'main/images/green-tea.png'%}"></img></a>
        </div>
        <div class = "right-objects navbar-block">
            {% if user.is_authenticated %}
            <div class = 'dropdown-user right-object'>
                <span class = 'profile'><i class="fa fa-user" aria-hidden="true"></i></span>
                <div class='dropdown-content-user'>
                    <div class = 'user-info'>
                        <div class = 'user-info-block'>
                            <p class = 'user-name user-text'>{{request.user.FirstName}} {{request.user.LastName}}</p>
                            <p class = 'user-email user-text'>{{request.user.email}}</p>
                        </div>
                    </div>
                    <a class = 'user-item-block' href = '#'>
                        <span class = 'user-item'>Профиль</span>
                    </a>
                    <a class = 'user-item-block' href = '{% url "user:logout" %}'>
                        <span class = 'user-item'>Выйти</span>
                    </a>
                </div>
                <script src = '{% static "main/js/LayOut/UserButton.js" %}'></script>
            </div>
            {% else %}
                <a class = 'profile right-object' href = '{% url "user:login" %}'><i class="fa fa-user" aria-hidden="true"></i> войти</a>
            {% endif %}
            <a class = 'cart-total right-object'  href = '#'><i class="fa fa-shopping-cart" aria-hidden="true"></i> корзина {{cart.lenght}}</a>
        </div>
    </nav>
    <nav class = "navbar-2">
        <div class = 'container'>
            {% for key, value in type.items %}

                <div class="dropdown">
                    <span class = 'dropdown-toggle'>{{key}}</span>
                    <div class="dropdown-content">
                        {% for type in value %}
                            <div class = 'link-container'>
                                <a class = 'type-link' href = '{% url "Catalog:catalog" key.typeslug type.slug %}' ><img  class = 'image-link' src = {{type.image.url}}></img>{{type.Type}} {{key}}</a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </nav>

    <main>
        {% block body %}
        {% endblock %}
    </main>
</body>
</html>

store/templates/main/login.html
{% extends 'main/layout.html' %}
{% load static %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class = 'main-container'>
        <div class = 'login-container'>
            <img class = 'logo-login' src = "{% static 'main/images/green-tea-icon.png'%}"></img>
            <p class = 'login-header'>Вход</p>
            <form method = 'POST' id = 'Login-form'>
                {% csrf_token %}
                <p class = 'field-header'>Почта</p>
                {{form.email}}
                <p class = 'error-field' id = 'email-field-error'></p>
                <p class = 'field-header margin-top'>Пароль</p>
                {{form.password}}
                <p class = 'error-field' id = 'password-field-error'></p>
                <br>
                <br>
                <button class = 'btn btn-success submit-btn' type = 'submit' id = 'submit-btn'>Войти</button>
            </form>
            <a class = 'register-link' href = '{% url "user:register" %}'>Нету аккаунта?</a>
        </div>
    </div>
    
    <script src="{% static 'main/js/LoginAjax.js' %}"></script>
    
    
{% endblock %}

store/templates/main/register.html
{% extends 'main/layout.html' %}
{% load static %}

{% block settings %}
    <link rel="stylesheet" href="{% static 'main/css/register.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/EmailSend.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class = 'main-container'>
        <div class = 'register-container'>
            <img class = 'logo-register' src = "{% static 'main/images/green-tea-icon.png'%}"></img>
            <p class = 'register-header'>Регистрация</p>
            <form method = 'POST' id = 'register-form'>
                {% csrf_token %}

                <p class = 'field-header'>Почта</p>
                {{form.email}}
                <p class = 'error-field' id = 'email-field-error'></p>

                <p class = 'field-header'>Имя</p>
                {{form.FirstName}}
                <p class = 'error-field' id = 'FirstName-field-error'></p>

                <p class = 'field-header'>фамилия</p>
                {{form.LastName}}
                <p class = 'error-field' id = 'LastName-field-error'></p>

                <p class = 'field-header margin-top'>Пароль</p>
                {{form.password}}
                <p class = 'error-field' id = 'password-field-error'></p>

                <p class = 'field-header margin-top'>Пароль (еще раз)</p>
                {{form.password_repeat}}
                <p class = 'error-field' id = 'password_repeat-field-error'></p>

                <br>
                <br>
                <button class = 'btn btn-success submit-btn' type = 'submit' id = 'submit-btn'>Зарегистрироваться</button>
            </form>
            <a class = 'login-link' href = '{% url "user:login" %}'>Уже есть аккаунт?</a>
        </div>
    </div>
    <br>
    <br>
    <br>
    
    <script src="{% static 'main/js/RegisterAjax.js' %}"></script>
    
    
{% endblock %}